name       : python-discid
version    : 1.2.0
release    : 6
source     :
    - https://github.com/JonnyJD/python-discid/archive/refs/tags/v1.2.0.tar.gz : 4eec56f054d960b66c4e42c711c317e987dd50c9e7267a29f7adadd9ceee664f
license    : LGPL-3.0-or-later
component  : programming.python
summary    : libdiscid python binding
description: |
    Python-discid implements Python bindings for MusicBrainz Libdiscid.
    Libdiscid's main purpose is the calculation of an identifier of audio discs (disc ID) to use for the MusicBrainz database.
    That identifier is calculated from the TOC of the disc, similar to the freeDB CDDB identifier. Libdiscid can calculate MusicBrainz disc IDs and freeDB disc IDs. Additionally the MCN of the disc and ISRCs from the tracks can be extracted.
builddeps  :
    - pkgconfig(libdiscid)
rundeps    :
    - libdiscid
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
