name       : python-discid
version    : 1.1.1
release    : 1
source     :
    - https://github.com/JonnyJD/python-discid/archive/v1.1.1.tar.gz : 5ed31ea16d752c0188f2d090cc60c38d8ca2a8b6e6dfb71a22499ca403aca19a
license    : LGPL-3.0-or-later
component  : programming.python
summary    : libdiscid python binding
description: |
    Python-discid implements Python bindings for MusicBrainz Libdiscid.
    Libdiscid's main purpose is the calculation of an identifier of audio discs (disc ID) to use for the MusicBrainz database.
    That identifier is calculated from the TOC of the disc, similar to the freeDB CDDB identifier. Libdiscid can calculate MusicBrainz disc IDs and freeDB disc IDs. Additionally the MCN of the disc and ISRCs from the tracks can be extracted.
builddeps  :
    - pkgconfig(libdiscid)
rundeps    :
    - libdiscid
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
